#!/bin/sh
# This file is generated by gen.py. Do not edit manually.
set -e

NAMESPACE=${NAMESPACE-toilal}
DOCKER_BUILD_OPTS=${DOCKER_BUILD_OPTS---pull}

echo "Push Dockerfile-py3-xenial-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-64bits
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-64bits
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-64bits
docker push $NAMESPACE/pyinstaller-linux:4.0-python3
docker push $NAMESPACE/pyinstaller-linux:4.0-64bits
docker push $NAMESPACE/pyinstaller-linux:4.0
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.7-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.7-xenial
docker push $NAMESPACE/pyinstaller-linux:python3-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:python3-xenial
docker push $NAMESPACE/pyinstaller-linux:64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:xenial
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.7-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.7-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-64bits
docker push $NAMESPACE/pyinstaller-linux:python3.7.9
docker push $NAMESPACE/pyinstaller-linux:python3.7-64bits
docker push $NAMESPACE/pyinstaller-linux:python3.7
docker push $NAMESPACE/pyinstaller-linux:python3-64bits
docker push $NAMESPACE/pyinstaller-linux:python3
docker push $NAMESPACE/pyinstaller-linux:64bits
docker push $NAMESPACE/pyinstaller-linux

echo "Push Dockerfile-py3-xenial-win64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-64bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-64bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-64bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3
docker push $NAMESPACE/pyinstaller-windows:4.0-64bits
docker push $NAMESPACE/pyinstaller-windows:4.0
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.7-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.7-xenial
docker push $NAMESPACE/pyinstaller-windows:python3-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3-xenial
docker push $NAMESPACE/pyinstaller-windows:64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:xenial
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.7-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.7-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-64bits
docker push $NAMESPACE/pyinstaller-windows:python3.7.9
docker push $NAMESPACE/pyinstaller-windows:python3.7-64bits
docker push $NAMESPACE/pyinstaller-windows:python3.7
docker push $NAMESPACE/pyinstaller-windows:python3-64bits
docker push $NAMESPACE/pyinstaller-windows:python3
docker push $NAMESPACE/pyinstaller-windows:64bits
docker push $NAMESPACE/pyinstaller-windows

echo "Push Dockerfile-py3-xenial-win32 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-32bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-32bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-32bits
docker push $NAMESPACE/pyinstaller-windows:4.0-32bits
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.7-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.7-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-32bits
docker push $NAMESPACE/pyinstaller-windows:python3.7-32bits
docker push $NAMESPACE/pyinstaller-windows:python3-32bits
docker push $NAMESPACE/pyinstaller-windows:32bits

echo "Push Dockerfile-py3-focal-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-focal
docker push $NAMESPACE/pyinstaller-linux:python3.7-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:python3.7-focal
docker push $NAMESPACE/pyinstaller-linux:python3-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:python3-focal
docker push $NAMESPACE/pyinstaller-linux:64bits-focal
docker push $NAMESPACE/pyinstaller-linux:focal
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.7-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.7-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:ubuntu20.04

echo "Push Dockerfile-py3-bionic-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.7-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.7-bionic
docker push $NAMESPACE/pyinstaller-linux:python3-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:python3-bionic
docker push $NAMESPACE/pyinstaller-linux:64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:bionic
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.7-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.7-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:ubuntu18.04

echo "Push Dockerfile-py3-bionic-win64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.7-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.7-bionic
docker push $NAMESPACE/pyinstaller-windows:python3-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3-bionic
docker push $NAMESPACE/pyinstaller-windows:64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:bionic
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.7-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.7-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:ubuntu18.04

echo "Push Dockerfile-py3-bionic-win32 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7.9-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.7-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.7-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.7.9-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.7-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:32bits-ubuntu18.04

echo "Push Dockerfile-py3-precise-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-precise
docker push $NAMESPACE/pyinstaller-linux:python3.7-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.7-precise
docker push $NAMESPACE/pyinstaller-linux:python3-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3-precise
docker push $NAMESPACE/pyinstaller-linux:64bits-precise
docker push $NAMESPACE/pyinstaller-linux:precise
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.7-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.7-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:ubuntu12.04

echo "Push Dockerfile-py3-precise-i386 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7.9-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.7-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.7-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:32bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.7.9-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.7-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:32bits-ubuntu12.04

echo "Push Dockerfile-py3-xenial-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-64bits
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-64bits
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.5-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.5-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.5-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.5-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-64bits
docker push $NAMESPACE/pyinstaller-linux:python3.5.9
docker push $NAMESPACE/pyinstaller-linux:python3.5-64bits
docker push $NAMESPACE/pyinstaller-linux:python3.5

echo "Push Dockerfile-py3-xenial-win64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-64bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-64bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.5-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.5-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.5-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.5-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-64bits
docker push $NAMESPACE/pyinstaller-windows:python3.5.9
docker push $NAMESPACE/pyinstaller-windows:python3.5-64bits
docker push $NAMESPACE/pyinstaller-windows:python3.5

echo "Push Dockerfile-py3-xenial-win32 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-32bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-32bits
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.5-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.5-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-32bits
docker push $NAMESPACE/pyinstaller-windows:python3.5-32bits

echo "Push Dockerfile-py3-focal-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-focal
docker push $NAMESPACE/pyinstaller-linux:python3.5-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:python3.5-focal
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.5-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.5-ubuntu20.04

echo "Push Dockerfile-py3-bionic-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.5-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.5-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.5-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.5-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.5-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.5-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.5-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.5-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win32 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5.9-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.5-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.5-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.5.9-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.5-32bits-ubuntu18.04

echo "Push Dockerfile-py3-precise-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-precise
docker push $NAMESPACE/pyinstaller-linux:python3.5-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.5-precise
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.5-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.5-ubuntu12.04

echo "Push Dockerfile-py3-precise-i386 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5.9-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.5-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.5-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.5.9-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.5-32bits-ubuntu12.04

echo "Push Dockerfile-py3-xenial-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-64bits
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-64bits
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.6-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.6-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.6-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.6-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-64bits
docker push $NAMESPACE/pyinstaller-linux:python3.6.12
docker push $NAMESPACE/pyinstaller-linux:python3.6-64bits
docker push $NAMESPACE/pyinstaller-linux:python3.6

echo "Push Dockerfile-py3-xenial-win64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-64bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-64bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.6-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.6-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.6-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.6-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-64bits
docker push $NAMESPACE/pyinstaller-windows:python3.6.12
docker push $NAMESPACE/pyinstaller-windows:python3.6-64bits
docker push $NAMESPACE/pyinstaller-windows:python3.6

echo "Push Dockerfile-py3-xenial-win32 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-32bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-32bits
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.6-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.6-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-32bits
docker push $NAMESPACE/pyinstaller-windows:python3.6-32bits

echo "Push Dockerfile-py3-focal-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-focal
docker push $NAMESPACE/pyinstaller-linux:python3.6-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:python3.6-focal
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.6-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.6-ubuntu20.04

echo "Push Dockerfile-py3-bionic-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.6-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.6-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.6-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.6-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.6-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.6-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.6-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.6-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win32 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6.12-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.6-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.6-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.6.12-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.6-32bits-ubuntu18.04

echo "Push Dockerfile-py3-precise-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-precise
docker push $NAMESPACE/pyinstaller-linux:python3.6-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.6-precise
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.6-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.6-ubuntu12.04

echo "Push Dockerfile-py3-precise-i386 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6.12-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.6-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.6-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.6.12-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.6-32bits-ubuntu12.04

echo "Push Dockerfile-py3-xenial-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-xenial
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-64bits
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-64bits
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.8-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.8-xenial
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.8-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.8-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-64bits
docker push $NAMESPACE/pyinstaller-linux:python3.8.5
docker push $NAMESPACE/pyinstaller-linux:python3.8-64bits
docker push $NAMESPACE/pyinstaller-linux:python3.8

echo "Push Dockerfile-py3-xenial-win64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-64bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-64bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.8-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.8-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.8-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.8-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-64bits
docker push $NAMESPACE/pyinstaller-windows:python3.8.5
docker push $NAMESPACE/pyinstaller-windows:python3.8-64bits
docker push $NAMESPACE/pyinstaller-windows:python3.8

echo "Push Dockerfile-py3-xenial-win32 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-32bits
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-32bits
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.8-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.8-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-32bits
docker push $NAMESPACE/pyinstaller-windows:python3.8-32bits

echo "Push Dockerfile-py3-focal-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-focal
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-focal
docker push $NAMESPACE/pyinstaller-linux:python3.8-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:python3.8-focal
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.8-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:python3.8-ubuntu20.04

echo "Push Dockerfile-py3-bionic-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-bionic
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.8-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.8-bionic
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.8-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:python3.8-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.8-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.8-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.8-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.8-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win32 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8.5-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:4.0-python3.8-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.8-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:python3.8.5-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:python3.8-32bits-ubuntu18.04

echo "Push Dockerfile-py3-precise-amd64 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-precise
docker push $NAMESPACE/pyinstaller-linux:python3.8-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.8-precise
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.8-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.8-ubuntu12.04

echo "Push Dockerfile-py3-precise-i386 (PYINSTALLER_VERSION=4.0 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8.5-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:4.0-python3.8-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.8-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:python3.8.5-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:python3.8-32bits-ubuntu12.04

echo "Push Dockerfile-py3-xenial-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3
docker push $NAMESPACE/pyinstaller-linux:3.6-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6

echo "Push Dockerfile-py3-xenial-win64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3
docker push $NAMESPACE/pyinstaller-windows:3.6-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6

echo "Push Dockerfile-py3-xenial-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-32bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-32bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-32bits
docker push $NAMESPACE/pyinstaller-windows:3.6-32bits

echo "Push Dockerfile-py3-focal-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-ubuntu20.04

echo "Push Dockerfile-py3-bionic-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7.9-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.7-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-32bits-ubuntu18.04

echo "Push Dockerfile-py3-precise-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-ubuntu12.04

echo "Push Dockerfile-py3-precise-i386 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.7.9)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7.9-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.7-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-32bits-ubuntu12.04

echo "Push Dockerfile-py2-trusty-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=2.7.17)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python2.7.17-32bits-trusty
docker push $NAMESPACE/pyinstaller-windows:3.6-python2.7-32bits-trusty
docker push $NAMESPACE/pyinstaller-windows:3.6-python2-32bits-trusty
docker push $NAMESPACE/pyinstaller-windows:3.6-python2.7.17-32bits-ubuntu14.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python2.7-32bits-ubuntu14.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python2-32bits-ubuntu14.04

echo "Push Dockerfile-py2-precise-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=2.7.17)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python2.7.17-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python2.7.17-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python2.7-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python2.7-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python2-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python2-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python2.7.17-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python2.7.17-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python2.7-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python2.7-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python2-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python2-ubuntu12.04

echo "Push Dockerfile-py3-xenial-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.3.7)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3

echo "Push Dockerfile-py3-xenial-win64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.3.7)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3

echo "Push Dockerfile-py3-xenial-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.3.7)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-32bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-32bits

echo "Push Dockerfile-py3-focal-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.3.7)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-ubuntu20.04

echo "Push Dockerfile-py3-bionic-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.3.7)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.3.7)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.3.7)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3.7-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.3-32bits-ubuntu18.04

echo "Push Dockerfile-py3-precise-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.3.7)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-ubuntu12.04

echo "Push Dockerfile-py3-precise-i386 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.3.7)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3.7-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.3-32bits-ubuntu12.04

echo "Push Dockerfile-py3-xenial-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.4.10)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4

echo "Push Dockerfile-py3-xenial-win64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.4.10)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4

echo "Push Dockerfile-py3-xenial-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.4.10)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-32bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-32bits

echo "Push Dockerfile-py3-focal-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.4.10)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-ubuntu20.04

echo "Push Dockerfile-py3-bionic-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.4.10)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.4.10)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.4.10)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4.10-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.4-32bits-ubuntu18.04

echo "Push Dockerfile-py3-precise-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.4.10)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-ubuntu12.04

echo "Push Dockerfile-py3-precise-i386 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.4.10)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4.10-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.4-32bits-ubuntu12.04

echo "Push Dockerfile-py3-xenial-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5

echo "Push Dockerfile-py3-xenial-win64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5

echo "Push Dockerfile-py3-xenial-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-32bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-32bits

echo "Push Dockerfile-py3-focal-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-ubuntu20.04

echo "Push Dockerfile-py3-bionic-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5.9-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.5-32bits-ubuntu18.04

echo "Push Dockerfile-py3-precise-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-ubuntu12.04

echo "Push Dockerfile-py3-precise-i386 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.5.9)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5.9-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.5-32bits-ubuntu12.04

echo "Push Dockerfile-py3-xenial-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6

echo "Push Dockerfile-py3-xenial-win64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6

echo "Push Dockerfile-py3-xenial-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-32bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-32bits

echo "Push Dockerfile-py3-focal-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-ubuntu20.04

echo "Push Dockerfile-py3-bionic-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6.12-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.6-32bits-ubuntu18.04

echo "Push Dockerfile-py3-precise-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-ubuntu12.04

echo "Push Dockerfile-py3-precise-i386 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.6.12)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6.12-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.6-32bits-ubuntu12.04

echo "Push Dockerfile-py3-xenial-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-64bits-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-xenial
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-ubuntu16.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-64bits
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8

echo "Push Dockerfile-py3-xenial-win64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-64bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-64bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-64bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8

echo "Push Dockerfile-py3-xenial-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-32bits-xenial
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-32bits-ubuntu16.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-32bits
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-32bits

echo "Push Dockerfile-py3-focal-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-64bits-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-focal
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-64bits-ubuntu20.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-ubuntu20.04

echo "Push Dockerfile-py3-bionic-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-64bits-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-bionic
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-64bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-64bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-ubuntu18.04

echo "Push Dockerfile-py3-bionic-win32 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-32bits-bionic
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8.5-32bits-ubuntu18.04
docker push $NAMESPACE/pyinstaller-windows:3.6-python3.8-32bits-ubuntu18.04

echo "Push Dockerfile-py3-precise-amd64 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-64bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-64bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-ubuntu12.04

echo "Push Dockerfile-py3-precise-i386 (PYINSTALLER_VERSION=3.6 PYTHON_VERSION=3.8.5)"
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-32bits-precise
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8.5-32bits-ubuntu12.04
docker push $NAMESPACE/pyinstaller-linux:3.6-python3.8-32bits-ubuntu12.04

